## A few more things on list: zip, enumerate

### ```enumerate(iterable, start=0)```

```enumerate()``` returns an enumerate object, i.e., an iterable object. It consists of tuples containing a count (from start which defaults to 0) and the values obtained from iterating over iterable.

In [1]:
v1 = [42, 1024, 23]
for i, v in enumerate(v1):
    print(i, v)

0 42
1 1024
2 23


In [2]:
v1 = [42, 1024, 23]
for i, v in enumerate(v1, start=1):
    print(i, v)

1 42
2 1024
3 23


### ```zip(*iterables)```

```zip()``` generates an iterator aggregates elements from each of the iterables.

In [3]:
v1 = [42, 1024, 23]
v2 =[6, 28, 496]
for a, b in zip(v1, v2):
    print(a, b)

42 6
1024 28
23 496


In [4]:
v1 = [42, 1024, 23]
v2 =[6, 28, 496, 8128]
for a, b in zip(v1, v2):
    print(a, b)

42 6
1024 28
23 496


### ```enumerate()``` with ```zip()```

In [5]:
v1 = [42, 1024, 23]
v2 =[6, 28, 496]
for i, (a, b) in enumerate(zip(v1, v2)):
    print(i, a, b)

0 42 6
1 1024 28
2 23 496


## function

A quick review of python functions.

In [6]:
# a very simple function
def add(x, y):
    return x + y

add(42, 23)

65

In [7]:
# function with a default value
def add(x, y, z=0):
    return x + y + z

print(add(42, 23))
print(add(42, 23, 1024))

65
1089


In [8]:
# None is frequently used as a default value to indicate nothing is passed
def add(x, y, z=None):
    if z != None:
        return x + y + z
    else:
        return x + y
    
print(add(42, 23))
print(add(42, 23, 1024))   

65
1089


In python, functions are first class objects; they can be assigned to variables as integers, lists, tuples, etc.

When assigning a function to a variable, you should not use (). If you add () at the end of a function name, a function is called.

After assigning a function to a variable, you can use the variable as a function. Remember that a variable is just an alias of an object. You can understand that a function has another name.

In [9]:
def add(x, y):
    return x + y

def substract(x, y):
    return x - y

op = add # op refers to add()
print(op(42, 23))
op = substract # op refers to substract()
print(op(42, 23))

65
19


## Lambda function

Python support lambda functions, i.e., function objects without a name. Typically, lambda function is a very short function.

In [10]:
add_l = lambda x, y: x + y
substract_l = lambda x, y: x - y

print(add_l(42, 23))
print(substract_l(42, 23))

65
19


## High order functions in python

High order functions either take one or more functions (or lambda expression) as parameter(s) or return a function. Here we will focus on the first case, where functions take other functions as parameters.

### ```map()```

In [11]:
vector = [1, 2, 3, 4, 5]
squared = []
for item in vector:
    squared.append(item ** 2)
squared

[1, 4, 9, 16, 25]

In [12]:
def square(x):
    return x * x

list(map(square, vector))

[1, 4, 9, 16, 25]

In [13]:
list(map(lambda x: x ** 2, vector))

[1, 4, 9, 16, 25]

In [14]:
# rough imitation of map() function
def func_map(func, iterable):
    result = []
    for item in iterable:
        result.append(func(item))
    return result

func_map(lambda x: x ** 2, vector)

[1, 4, 9, 16, 25]

### ```filter()```

`filter()``` creates a list of elements for which a function returns true.

In [15]:
list(filter(lambda x: x % 2 == 0, vector))

[2, 4]

### ```reduce()```

```reduce()``` applies a rolling computation to sequential pairs of values in a list.

In [16]:
product = 1
list = [1, 2, 3, 4]
for num in list:
    product = product * num
product

24

The above for loop can be abbreviated into one line using ```reduce()``` function.

In [17]:
from functools import reduce
product = reduce(lambda x, y: x * y, [1, 2, 3, 4])
product

24

## numpy

### Making arrays from list

In [18]:
# in almost every python code, numpy is imported as the following form
import numpy as np

vector = [42, 1024, 23]
x = np.array(vector)
print(type(x))
print(x.shape)
print(x.ndim)
print(x[0], x[1], x[2])
print(x)

<class 'numpy.ndarray'>
(3,)
1
42 1024 23
[  42 1024   23]


In [19]:
y = np.array([[42, 1024, 23], [6, 28, 496]])
print(type(y))
print(y.shape)
print(y.ndim)
print(y[0][0], y[0,1]) # both form is valid, but , notation is more common with numpy

<class 'numpy.ndarray'>
(2, 3)
2
42 1024


### Making arrays with numpy functions

In [20]:
x = np.arange(0, 30, 2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [21]:
x.reshape(3, 5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [22]:
y = np.linspace(0, 4, 9) # from 0 to 4 with 9 samples
print(y.shape)
y

(9,)


array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [23]:
z = np.linspace(0, 4, 9, endpoint=False) # doesn't include the end point
print(z.shape)
z

(9,)


array([ 0.        ,  0.44444444,  0.88888889,  1.33333333,  1.77777778,
        2.22222222,  2.66666667,  3.11111111,  3.55555556])

In [24]:
yy = y.reshape(3, 3)
yy

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [25]:
np.zeros((2, 3)) # you should pass tuple

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [26]:
np.zeros_like(yy)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

ones(), ones_like(), empty(), empty_like(), eye() can be used in a similar way.

### Indexing/sliding of arrays

In [27]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)
print(x[1][2], x[1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7 7


In [28]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
y = x[:2, 1:3]
print(x)
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


**Important: ** slicing in numpy array DO NOT make a new array.

In [29]:
y[0,0] = 42
print(x)
print(y)

[[ 1 42  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[42  3]
 [ 6  7]]


### Transpose

**Important: ** transpose share the same data.

In [30]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
y = x.T
print(x)
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [31]:
y[3,2] = 42
print(x)
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 42]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 42]]


### Operations on arrays

In [32]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
y = np.ones_like(x)
x + y # itemwise sum

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [33]:
x ** 2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

### Boolean indexing

**Important:** Boolean indexing generates a new array

In [34]:
a = np.arange(1, 30, 3)
print(a)

[ 1  4  7 10 13 16 19 22 25 28]


In [35]:
bool_index = a >= 15
bool_index

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [36]:
a[bool_index]

array([16, 19, 22, 25, 28])

In [37]:
a[a >= 15]

array([16, 19, 22, 25, 28])

In [38]:
a[(a >= 15) & (a <= 30)]

array([16, 19, 22, 25, 28])

In [39]:
a[(a >= 15) & (a % 2 == 0)]

array([16, 22, 28])